version: '3.5'

services:
  postgres:
    image: postgres
    container_name: timeless-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
